apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-bloom-filter-service
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: bloom-filter
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.project.name }}
  source:
    path: deployment
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}