apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.project.name }}
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: Sample project for Node.js applications
  destinations:
    - name: local-cluster
      namespace: '*'
      server: {{ .Values.spec.destination.server }}
    - name: {{ .Values.cluster.name }}
      namespace: '*'
      server: {{ .Values.cluster.server }}
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'